# Generated by Django 5.0 on 2026-03-25 20:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The headline of the post', max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of the title', max_length=200, unique=True)),
                ('content', models.TextField(help_text='The main body of the post')),
                ('author', models.CharField(help_text='Name of the author', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the post was created')),
                ('published', models.BooleanField(default=False, help_text='Is this post visible to the public?')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
